pipeline {
	agent any
	stages {
		stage('Stage 1'){
			steps {
				echo 'Hello!'
				sh 'mvn clean'	
			}
		}
		stage('Stage 2'){
			steps {
				echo 'I am...'
				sh 'mvn package'	
			}
		}
		stage('Stage 3'){
			steps {
				echo 'I am testing..'
				sh 'mvn test'
			}
		}
		
	}
}















