pipeline {
	agent any
	environment{
		PATH = "/sbin:/usr/sbin:/bin:/usr/bin:/opt/apache-maven-3.6.1/bin"
		M2_HOME = "/opt/apache-maven-3.6.1"
	}
	stages {
		stage('Stage 1'){
			steps {
				echo 'Hello!'
				sh 'mvn clean'	
			}
		}
		stage('Stage 2'){
			steps {
				echo 'I am...'
				sh 'mvn package'	
			}
		}
		stage('Stage 3'){
			steps {
				echo 'I am testing..'
				sh 'mvn test'
			}
		}
		
	}
}















